version: "3.9"

services:
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"

  mongo:
    container_name: mongo
    image: mongo

  sendhooks-engine:
    container_name: sendhooks-engine
    image: transfa/sendhooks:latest
    volumes:
      - ./config.json:/root/config.json
    depends_on:
      - mongo
      - redis

  sendhooks-monitoring:
    container_name: sendhooks-monitoring
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    ports:
      - "5002:5002"
      - "3000:3000"
    depends_on:
      - mongo
      - sendhooks-engine
      - redis
