version: "3.9"

# Define the services that make up your application so they can be run together in an isolated environment.
services:
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379" # this makes the service available on the localhost via 6379.

  mongo:
    container_name: mongo
    image: mongo

  sendhooks-engine:
    container_name: sendhooks-engine
    image: transfa/sendhooks:latest
    volumes:
      - ./config.json:/root/config.json
    depends_on:
      - mongo
      - redis

  # Define the main application service (sendhooks-engine-api).
  sendhooks-engine-api:
    container_name: sendhooks-engine-api
    build: .
    env_file:
      - ./.env.local # Load environment variables from a file named .env in the current directory.
    ports:
      - "5002:5002" # Map port 5002 on the host to port 5001 in the container, making the application accessible.
    depends_on:
      - mongo
